import org.openmdx.portal.servlet.*;
import org.openmdx.portal.servlet.texts.*;
import org.openmdx.portal.servlet.view.*;
import org.openmdx.portal.servlet.control.*;

ApplicationContext app = p.getApplicationContext();        
p.write("<table id=\"headerlayout\" style=\"position:relative;\">");
p.write("  <tr id=\"headRow\">");
p.write("    <td id=\"head\" colspan=\"2\">");
p.write("      <table id=\"info\">");
p.write("        <tr>");
p.write("          <td id=\"headerCellLeft\"><img id=\"logoLeft\" src=\"", p.getResourcePath("images/"), "logoLeft.gif\" alt=\"", app.getApplicationName(), "\" title=\"\" /></td>");
p.write("          <td id=\"headerCellSpacerLeft\"></td>");
p.write("          <td id=\"headerCellMiddle\">");
p.write("            <table id=\"headerMiddleLayout\">");
p.write("              <tr>");
p.write("                <td>");
SessionInfoControl.paintLoginPrincipal(p);
p.write("                </td>");
p.write("                <td>");
SessionInfoControl.paintLocalesMenu(p, forEditing);
p.write("                </td>");
p.write("                <td>");
SessionInfoControl.paintLogoffButton(p, forEditing, "abutton");
p.write("                </td>");
p.write("              </tr>");
p.write("              <tr>");    
p.write("                <td>");        
SessionInfoControl.paintRolesMenu(p, forEditing);
p.write("                </td>");
p.write("                <td>");
SessionInfoControl.paintGuiModesMenu(p, forEditing);
p.write("                </td>");
p.write("                <td>");
SessionInfoControl.paintSaveSettingsButton(p, forEditing, "abutton");
p.write("                </td>");
p.write("              </tr>");
p.write("            </table>");
p.write("          </td>");
p.write("          <td id=\"headerCellRight\"><img id=\"logoRight\" src=\"", p.getResourcePath("images/"), "logoRight.gif\" alt=\"\" title=\"\" /></td>");
p.write("        </tr>");
p.write("      </table>");
p.write("    </td>");
p.write("  </tr>");
p.write("</table>");                
