<?xml version="1.0" encoding="UTF-8"?>
<definitions name="dataprovider" targetNamespace="http://127.0.0.1:7001/webservices/dataprovider" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	
	<import namespace="http://127.0.0.1:7001/webservices/dataprovider"
           location="http://127.0.0.1:7001/webservices/dataprovider_1.xsd"/>
           
	<message name="processInput">
		<part name="ServiceHeader" type="ServiceHeader"/>
		<part name="UnitOfWorkRequestList" type="UnitOfWorkRequestList"/>
	</message>
	<message name="processOutput">
		<part name="UnitOfWorkReplyList" type="UnitOfWorkReplyList"/>
	</message>
	<portType name="DataproviderPortType">
		<operation name="process" parameterOrder="ServiceHeader UnitOfWorkRequestList">
			<input message="tns:processInput"/>
			<output message="tns:processOutput"/>
		</operation>
	</portType>
	<binding name="DataproviderBinding" type="tns:DataproviderPortType">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="process">
			<soap:operation style="rpc"/>
			<input>
				<soap:body use="encoded" namespace="http://127.0.0.1:7001/webservices/dataprovider" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</input>
			<output>
				<soap:body use="encoded" namespace="http://127.0.0.1:7001/webservices/dataprovider" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</output>
		</operation>
	</binding>
	<service name="DataproviderService">
		<documentation>Dataprovider Service</documentation>
		<port name="DataproviderPort" binding="tns:DataproviderBinding">
			<soap:address location="http://127.0.0.1:7001/webservices/dataprovider"/>
		</port>
	</service>
</definitions>
