git add ant/build.xml
git add ant/etc/ant/build-library.xml
git add ant/etc/ant/build-properties.xml
git add ant/etc/ant/jre-1.5-properties.xml
git add ant/etc/ant/jre-1.6-properties.xml
git add ant/etc/ant/jre-1.7-properties.xml
git add apache/jre-1.6/commons/.classpath
git add apache/jre-1.6/commons/.project
git add apache/jre-1.6/commons/lib/commons-beanutils.jar
git add apache/jre-1.6/commons/lib/commons-codec.jar
git add apache/jre-1.6/commons/lib/commons-collections.jar
git add apache/jre-1.6/commons/lib/commons-digester.jar
git add apache/jre-1.6/commons/lib/commons-el.jar
git add apache/jre-1.6/commons/lib/commons-fileupload.jar
git add apache/jre-1.6/commons/lib/commons-httpclient.jar
git add apache/jre-1.6/commons/lib/commons-lang.jar
git add apache/jre-1.6/myfaces/.classpath
git add apache/jre-1.6/myfaces/.project
git add apache/jre-1.6/myfaces/lib/myfaces-api.jar
git add apache/jre-1.6/myfaces/lib/myfaces-impl.jar
git add apache/jre-1.6/myfaces/src/myfaces-api.zip
git add apache/jre-1.6/myfaces/src/myfaces-impl.zip
git add apache/jre-1.6/openejb/.classpath
git add apache/jre-1.6/openejb/lib/XmlSchema.jar
git rm apache/jre-1.6/openejb/lib/activeio-core-incubator.jar
git add apache/jre-1.6/openejb/lib/activeio-core.jar
git add apache/jre-1.6/openejb/lib/activemq-core.jar
git add apache/jre-1.6/openejb/lib/activemq-protobuf.jar
git add apache/jre-1.6/openejb/lib/activemq-ra.jar
git rm apache/jre-1.6/openejb/lib/backport-util-concurrent.jar
git add apache/jre-1.6/openejb/lib/bcprov-jdk15.jar
git add apache/jre-1.6/openejb/lib/commons-logging-api.jar
git add apache/jre-1.6/openejb/lib/commons-net.jar
git add apache/jre-1.6/openejb/lib/cxf-bundle.jar
git add apache/jre-1.6/openejb/lib/ejb31-api-experimental.jar
git add apache/jre-1.6/openejb/lib/geronimo-j2ee-management.jar
git add apache/jre-1.6/openejb/lib/geronimo-j2ee-management_spec.jar
git add apache/jre-1.6/openejb/lib/geronimo-javamail.jar
git add apache/jre-1.6/openejb/lib/geronimo-jms_spec.jar
git add apache/jre-1.6/openejb/lib/javaee-api.jar
git add apache/jre-1.6/openejb/lib/jaxb-impl.jar
git add apache/jre-1.6/openejb/lib/kahadb.jar
git add apache/jre-1.6/openejb/lib/openejb-api.jar
git add apache/jre-1.6/openejb/lib/openejb-client.jar
git add apache/jre-1.6/openejb/lib/openejb-core.jar
git add apache/jre-1.6/openejb/lib/openejb-cxf.jar
git add apache/jre-1.6/openejb/lib/openejb-ejbd.jar
git add apache/jre-1.6/openejb/lib/openejb-hsql.jar
git add apache/jre-1.6/openejb/lib/openejb-http.jar
git add apache/jre-1.6/openejb/lib/openejb-javaagent.jar
git add apache/jre-1.6/openejb/lib/openejb-jee.jar
git add apache/jre-1.6/openejb/lib/openejb-loader.jar
git add apache/jre-1.6/openejb/lib/openejb-multicast.jar
git add apache/jre-1.6/openejb/lib/openejb-server.jar
git add apache/jre-1.6/openejb/lib/openejb-telnet.jar
git add apache/jre-1.6/openejb/lib/openejb-tomcat-catalina.jar
git add apache/jre-1.6/openejb/lib/openejb-tomcat-common.jar
git add apache/jre-1.6/openejb/lib/openejb-tomcat-loader.jar
git add apache/jre-1.6/openejb/lib/openejb-tomcat-webapp-sources.jar
git add apache/jre-1.6/openejb/lib/openejb-tomcat-webapp.jar
git add apache/jre-1.6/openejb/lib/openejb-webapp-common.jar
git add apache/jre-1.6/openejb/lib/openejb-webservices.jar
git rm apache/jre-1.6/openejb/lib/opensaml.jar
git add apache/jre-1.6/openejb/lib/saaj-impl.jar
git add apache/jre-1.6/openejb/lib/wss4j.jar
git add apache/jre-1.6/openejb/lib/xbean-asm-shaded.jar
git add apache/jre-1.6/openejb/lib/xbean-finder-shaded.jar
git add apache/jre-1.6/openejb/lib/xbean-naming.jar
git add apache/jre-1.6/openejb/lib/xbean-reflect.jar
git add apache/jre-1.6/openejb/lib/xmlsec.jar
git add apache/jre-1.6/openejb/src/openejb-api.zip
git add apache/jre-1.6/openejb/src/openejb-cfx.zip
git add apache/jre-1.6/openejb/src/openejb-client.zip
git add apache/jre-1.6/openejb/src/openejb-core.zip
git add apache/jre-1.6/openejb/src/openejb-ejbd.zip
git add apache/jre-1.6/openejb/src/openejb-hsql.zip
git add apache/jre-1.6/openejb/src/openejb-http.zip
git add apache/jre-1.6/openejb/src/openejb-javaagent.zip
git add apache/jre-1.6/openejb/src/openejb-jee.zip
git add apache/jre-1.6/openejb/src/openejb-loader.zip
git add apache/jre-1.6/openejb/src/openejb-server.zip
git add apache/jre-1.6/openejb/src/openejb-telnet.zip
git add apache/jre-1.6/openejb/src/openejb-tomcat-catalina.zip
git add apache/jre-1.6/openejb/src/openejb-tomcat-common.zip
git add apache/jre-1.6/openejb/src/openejb-tomcat-loader.zip
git add apache/jre-1.6/openejb/src/openejb-tomcat-webapp.zip
git add apache/jre-1.6/openejb/src/openejb-webservices.zip
git add apache/jre-1.6/openejb/war/openejb.war
git rm apache/jre-1.6/tomcat/.classpath
git rm apache/jre-1.6/tomcat/.project
git rm apache/jre-1.6/tomcat/lib/annotations-api.jar
git rm apache/jre-1.6/tomcat/lib/catalina-ant.jar
git rm apache/jre-1.6/tomcat/lib/catalina-ha.jar
git rm apache/jre-1.6/tomcat/lib/catalina-tribes.jar
git rm apache/jre-1.6/tomcat/lib/catalina.jar
git rm apache/jre-1.6/tomcat/lib/el-api.jar
git rm apache/jre-1.6/tomcat/lib/jasper-el.jar
git rm apache/jre-1.6/tomcat/lib/jasper-jdt.jar
git rm apache/jre-1.6/tomcat/lib/jasper.jar
git rm apache/jre-1.6/tomcat/lib/jsp-api.jar
git rm apache/jre-1.6/tomcat/lib/servlet-api.jar
git rm apache/jre-1.6/tomcat/lib/tomcat-coyote.jar
git rm apache/jre-1.6/tomcat/lib/tomcat-dbcp.jar
git rm apache/jre-1.6/tomcat/lib/tomcat-i18n-es.jar
git rm apache/jre-1.6/tomcat/lib/tomcat-i18n-fr.jar
git rm apache/jre-1.6/tomcat/lib/tomcat-i18n-ja.jar
git rm apache/jre-1.6/tomcat/lib/tomcat-juli.jar
git rm apache/jre-1.6/tomcat/src/catalina.zip
git add apache/jre-1.6/tomcat7/.classpath
#	renamed:    apache/jre-1.6/tomcat/.cvsignore -> apache/jre-1.6/tomcat7/.cvsignore
git add apache/jre-1.6/tomcat7/.project
git add apache/jre-1.6/tomcat7/lib/annotations-api.jar
git add apache/jre-1.6/tomcat7/lib/catalina-ant.jar
git add apache/jre-1.6/tomcat7/lib/catalina-ha.jar
git add apache/jre-1.6/tomcat7/lib/catalina-tribes.jar
git add apache/jre-1.6/tomcat7/lib/catalina.jar
git add apache/jre-1.6/tomcat7/lib/ecj-3.6.jar
git add apache/jre-1.6/tomcat7/lib/el-api.jar
git add apache/jre-1.6/tomcat7/lib/jasper-el.jar
git add apache/jre-1.6/tomcat7/lib/jasper.jar
git add apache/jre-1.6/tomcat7/lib/jsp-api.jar
git add apache/jre-1.6/tomcat7/lib/servlet-api.jar
git add apache/jre-1.6/tomcat7/lib/tomcat-api.jar
git add apache/jre-1.6/tomcat7/lib/tomcat-coyote.jar
git add apache/jre-1.6/tomcat7/lib/tomcat-dbcp.jar
git add apache/jre-1.6/tomcat7/lib/tomcat-i18n-es.jar
git add apache/jre-1.6/tomcat7/lib/tomcat-i18n-fr.jar
git add apache/jre-1.6/tomcat7/lib/tomcat-i18n-ja.jar
git add apache/jre-1.6/tomcat7/lib/tomcat-juli.jar
git add apache/jre-1.6/tomcat7/lib/tomcat-util.jar
git add apache/jre-1.6/tomcat7/src/catalina.zip
git add apache/jre-1.6/tomcat7/src/tomcat-dbcp.zip
git add build.xml
git add codehaus/jre-1.7/groovy/.classpath
git add codehaus/jre-1.7/groovy/.cvsignore
git add codehaus/jre-1.7/groovy/.project
git add codehaus/jre-1.7/groovy/.settings/org.eclipse.core.resources.prefs
git add codehaus/jre-1.7/groovy/lib/groovy.jar
git add codehaus/jre-1.7/groovy/src/groovy-src.zip
git add core.jre-1.5/.classpath
git add core.jre-1.5/.project
git add core/CHANGE-LOG
git add core/RELEASE-NOTES
git add core/build.xml
git add core/etc/ant/Version.java-deprecated.template
git add core/etc/javadoc/openmdx/package-list
git add core/jre-1.5-properties.xml
git add core/jre-1.6-properties.xml
git add core/jre-1.7-properties.xml
git add core/src/java/javax/jmi/model/AggregationKindEnum.java
git add core/src/java/javax/jmi/model/Aliases.java
git add core/src/java/javax/jmi/model/AttachesTo.java
git add core/src/java/javax/jmi/model/CanRaise.java
git add core/src/java/javax/jmi/model/Constrains.java
git add core/src/java/javax/jmi/model/Constraint.java
git add core/src/java/javax/jmi/model/Contains.java
git add core/src/java/javax/jmi/model/DependsOn.java
git add core/src/java/javax/jmi/model/DirectionKindEnum.java
git add core/src/java/javax/jmi/model/EnumerationType.java
git add core/src/java/javax/jmi/model/EnumerationTypeClass.java
git add core/src/java/javax/jmi/model/EvaluationKindEnum.java
git add core/src/java/javax/jmi/model/Exposes.java
git add core/src/java/javax/jmi/model/GeneralizableElement.java
git add core/src/java/javax/jmi/model/Generalizes.java
git add core/src/java/javax/jmi/model/IsOfType.java
git add core/src/java/javax/jmi/model/ModelElement.java
git add core/src/java/javax/jmi/model/NameNotResolvedException.java
git add core/src/java/javax/jmi/model/Namespace.java
git add core/src/java/javax/jmi/model/Operation.java
git add core/src/java/javax/jmi/model/RefersTo.java
git add core/src/java/javax/jmi/model/ScopeKindEnum.java
git add core/src/java/javax/jmi/model/Tag.java
git add core/src/java/javax/jmi/model/TagClass.java
git add core/src/java/javax/jmi/model/VisibilityKindEnum.java
git add core/src/java/javax/jmi/reflect/RefAssociation.java
git add core/src/java/javax/jmi/reflect/RefBaseObject.java
git add core/src/java/javax/jmi/reflect/RefClass.java
git add core/src/java/javax/jmi/reflect/RefEnum.java
git add core/src/java/javax/jmi/reflect/RefFeatured.java
git add core/src/java/javax/jmi/reflect/RefPackage.java
git add core/src/java/javax/jmi/reflect/RefStruct.java
git add core/src/java/javax/jmi/reflect/TypeMismatchException.java
git add core/src/java/javax/jmi/xmi/XmiReader.java
git add core/src/java/javax/jmi/xmi/XmiWriter.java
git add core/src/java/org/omg/mof/spi/Names.java
git add core/src/java/org/openmdx/application/cci/ConfigurationSpecifier.java
git add core/src/java/org/openmdx/application/dataprovider/accessor/Object_1.java
git add core/src/java/org/openmdx/application/dataprovider/cci/AttributeSpecifier.java
git add core/src/java/org/openmdx/application/dataprovider/cci/DataproviderRequest.java
git add core/src/java/org/openmdx/application/dataprovider/cci/DataproviderRequestProcessor.java
git add core/src/java/org/openmdx/application/dataprovider/cci/FilterProperty.java
git add core/src/java/org/openmdx/application/dataprovider/cci/JmiHelper.java
git add core/src/java/org/openmdx/application/dataprovider/cci/RequestedMessage.java
git add core/src/java/org/openmdx/application/dataprovider/cci/RequestedObject.java
git add core/src/java/org/openmdx/application/dataprovider/cci/ServiceHeader.java
git add core/src/java/org/openmdx/application/dataprovider/cci/SharedConfigurationEntries.java
git add core/src/java/org/openmdx/application/dataprovider/kernel/Dataprovider_1.java
git add core/src/java/org/openmdx/application/dataprovider/layer/application/Standard_1.java
git add core/src/java/org/openmdx/application/dataprovider/layer/interception/Standard_1.java
git add core/src/java/org/openmdx/application/dataprovider/layer/model/LayerConfigurationEntries.java
git add core/src/java/org/openmdx/application/dataprovider/layer/model/Standard_1.java
git add core/src/java/org/openmdx/application/dataprovider/layer/model/State_1_Attributes.java
git add core/src/java/org/openmdx/application/dataprovider/layer/model/State_2.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/common/AbstractPersistence_1.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/AbstractDatabase_1.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/DBOSlicedWithIdAsKey.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/DBOSlicedWithParentAndIdAsKey.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/DatabaseConfiguration.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/Database_1.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/Datums.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/DbObject.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/DbObjectConfiguration.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/DurationMarshaller.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/FastResultSet.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/GenericBlob.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/GenericClob.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/LayerConfigurationEntries.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/RidOidQueryDatabase_1.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/SlicedDbObject.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/SlicedDbObject2.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/SlicedDbObject2NonIndexed.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/SlicedDbObject2NonIndexedParentRidOnly.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/SlicedDbObject2ParentRidOnly.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/SlicedDbObjectParentRidOnly.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/StandardDbObject.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/jdbc/XMLGregorianCalendarMarshaller.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/none/InMemory_1.java
git rm core/src/java/org/openmdx/application/dataprovider/layer/persistence/none/LayerConfigurationEntries.java
git add core/src/java/org/openmdx/application/dataprovider/layer/persistence/none/MappedRecordFilter.java
git add core/src/java/org/openmdx/application/dataprovider/layer/type/Strict_1.java
git add core/src/java/org/openmdx/application/dataprovider/spi/AbstractComparator.java
git add core/src/java/org/openmdx/application/dataprovider/spi/AbstractFilter.java
git add core/src/java/org/openmdx/application/dataprovider/spi/Layer_1.java
git add core/src/java/org/openmdx/application/dataprovider/spi/OperationAwareLayer_1.java
git add core/src/java/org/openmdx/application/dataprovider/spi/ResourceHelper.java
git add core/src/java/org/openmdx/application/mof/externalizer/rose/RoseImporter_1.java
git add core/src/java/org/openmdx/application/mof/externalizer/spi/ModelImporter_1.java
git add core/src/java/org/openmdx/application/mof/externalizer/spi/Model_1Accessor.java
git add core/src/java/org/openmdx/application/mof/externalizer/xmi/XMI1Parser.java
git add core/src/java/org/openmdx/application/mof/externalizer/xmi/XMI1ReferenceResolver.java
git add core/src/java/org/openmdx/application/mof/externalizer/xmi/XMI20Parser.java
git add core/src/java/org/openmdx/application/mof/externalizer/xmi/XMI2Parser.java
git add core/src/java/org/openmdx/application/mof/externalizer/xmi/XMI2ReferenceResolver.java
git add core/src/java/org/openmdx/application/mof/externalizer/xmi/XMIImporter_1.java
git add core/src/java/org/openmdx/application/mof/externalizer/xmi/XMIParser.java
git add core/src/java/org/openmdx/application/mof/externalizer/xmi/uml1/UML1Association.java
git add core/src/java/org/openmdx/application/mof/externalizer/xmi/uml1/UML1AssociationEnd.java
git add core/src/java/org/openmdx/application/mof/externalizer/xmi/uml1/UML1Class.java
git add core/src/java/org/openmdx/application/mof/externalizer/xmi/uml1/UML1Classifier.java
git add core/src/java/org/openmdx/application/mof/externalizer/xmi/uml1/UML1ModelElement.java
git add core/src/java/org/openmdx/application/mof/externalizer/xmi/uml1/UML1Operation.java
git add core/src/java/org/openmdx/application/mof/mapping/cci/AssociationEndDef.java
git add core/src/java/org/openmdx/application/mof/mapping/cci/AttributeDef.java
git add core/src/java/org/openmdx/application/mof/mapping/cci/ClassDef.java
git add core/src/java/org/openmdx/application/mof/mapping/cci/ClassifierDef.java
git add core/src/java/org/openmdx/application/mof/mapping/cci/ElementDef.java
git add core/src/java/org/openmdx/application/mof/mapping/cci/ExceptionDef.java
git add core/src/java/org/openmdx/application/mof/mapping/cci/FeatureDef.java
git add core/src/java/org/openmdx/application/mof/mapping/cci/MappingTypes.java
git add core/src/java/org/openmdx/application/mof/mapping/cci/OperationDef.java
git add core/src/java/org/openmdx/application/mof/mapping/cci/ReferenceDef.java
git add core/src/java/org/openmdx/application/mof/mapping/cci/StructDef.java
git add core/src/java/org/openmdx/application/mof/mapping/cci/StructuralFeatureDef.java
git add core/src/java/org/openmdx/application/mof/mapping/java/AbstractClassMapper.java
git add core/src/java/org/openmdx/application/mof/mapping/java/AbstractMapper.java
git add core/src/java/org/openmdx/application/mof/mapping/java/AbstractMetaDataMapper.java
git add core/src/java/org/openmdx/application/mof/mapping/java/ClassMapper.java
git add core/src/java/org/openmdx/application/mof/mapping/java/ClassType.java
git add core/src/java/org/openmdx/application/mof/mapping/java/ExceptionMapper.java
git add core/src/java/org/openmdx/application/mof/mapping/java/InstanceMapper.java
git add core/src/java/org/openmdx/application/mof/mapping/java/Mapper_1.java
git rm core/src/java/org/openmdx/application/mof/mapping/java/MetaDataMapper.java
git add core/src/java/org/openmdx/application/mof/mapping/java/MetaData_2.java
git add core/src/java/org/openmdx/application/mof/mapping/java/NativeMetaDataMapper.java
git add core/src/java/org/openmdx/application/mof/mapping/java/PackageMapper.java
git add core/src/java/org/openmdx/application/mof/mapping/java/QueryMapper.java
git add core/src/java/org/openmdx/application/mof/mapping/java/StandardMetaDataMapper.java
git add core/src/java/org/openmdx/application/mof/mapping/java/StructureMapper.java
git add core/src/java/org/openmdx/application/mof/mapping/java/metadata/JoinMetaData.java
git add core/src/java/org/openmdx/application/mof/mapping/spi/MapperFactory_1.java
git rm core/src/java/org/openmdx/application/mof/mapping/together/TogetherMapper_1.java
git rm core/src/java/org/openmdx/application/mof/mapping/together/UmlMapper.java
git add core/src/java/org/openmdx/application/mof/mapping/xmi/Uml1Mapper_1.java
git add core/src/java/org/openmdx/application/mof/mapping/xmi/Uml1ModelMapper.java
git add core/src/java/org/openmdx/application/mof/mapping/xmi/Uml2Mapper_1.java
git add core/src/java/org/openmdx/application/mof/mapping/xmi/Uml2ModelMapper.java
git add core/src/java/org/openmdx/application/mof/mapping/xmi/XMIMapper_1.java
git add core/src/java/org/openmdx/application/mof/mapping/xmi/XMIModelMapper.java
git add core/src/java/org/openmdx/application/mof/mapping/xmi/XMISchemaMapper.java
git add core/src/java/org/openmdx/application/mof/repository/accessor/ModelElement_1.java
git add core/src/java/org/openmdx/application/mof/repository/accessor/Model_1.java
git add core/src/java/org/openmdx/application/mof/repository/layer/application/ModelConstraintsChecker_1.java
git add core/src/java/org/openmdx/application/mof/repository/layer/application/Model_1.java
git add core/src/java/org/openmdx/application/mof/repository/layer/model/Model_1.java
git add core/src/java/org/openmdx/application/mof/repository/layer/type/Model_1.java
git add core/src/java/org/openmdx/application/mof/repository/utils/ModelUtils.java
git add core/src/java/org/openmdx/application/rest/ejb/DataManager_2ProxyFactory.java
git add core/src/java/org/openmdx/application/rest/http/BooleanCallback.java
git add core/src/java/org/openmdx/application/rest/http/CallbackPrompts.java
git add core/src/java/org/openmdx/application/rest/http/HttpPort.java
git add core/src/java/org/openmdx/application/rest/http/RemoteUserLoginModule.java
git add core/src/java/org/openmdx/application/rest/http/RequestCallbackHandler.java
git add core/src/java/org/openmdx/application/rest/http/RestServlet_2.java
git add core/src/java/org/openmdx/application/rest/http/SimplePort.java
git add core/src/java/org/openmdx/application/rest/http/TrustingLoginModule.java
git add core/src/java/org/openmdx/application/rest/spi/EntityManagerProxyFactory_2.java
git add core/src/java/org/openmdx/application/rest/spi/InboundConnectionFactory_2.java
git add core/src/java/org/openmdx/application/rest/spi/ProxyPlugIn_1.java
git add core/src/java/org/openmdx/application/spi/NamingConfigurationProvider.java
git add core/src/java/org/openmdx/application/xml/Exporter.java
git add core/src/java/org/openmdx/application/xml/jmi/BasicImportPlugIn.java
git add core/src/java/org/openmdx/application/xml/jmi/StateImportPlugIn.java
git add core/src/java/org/openmdx/application/xml/spi/DataproviderTarget.java
git add core/src/java/org/openmdx/application/xml/spi/ExportFilter.java
git add core/src/java/org/openmdx/application/xml/spi/ExportTarget.java
git add core/src/java/org/openmdx/application/xml/spi/ImportHandler.java
git add core/src/java/org/openmdx/application/xml/spi/XMLTarget.java
git add core/src/java/org/openmdx/audit2/aop0/PlugIn_1.java
git add core/src/java/org/openmdx/audit2/aop1/Involvement_1.java
git add core/src/java/org/openmdx/audit2/cci/AuditQueries.java
git add core/src/java/org/openmdx/audit2/spi/Qualifiers.java
git add core/src/java/org/openmdx/base/accessor/cci/DataObjectManager_1_0.java
git add core/src/java/org/openmdx/base/accessor/cci/SystemAttributes.java
git add core/src/java/org/openmdx/base/accessor/jmi/cci/JmiServiceException.java
git add core/src/java/org/openmdx/base/accessor/jmi/spi/EntityManagerFactory_1.java
git add core/src/java/org/openmdx/base/accessor/jmi/spi/FeatureMapper.java
git add core/src/java/org/openmdx/base/accessor/jmi/spi/ImplementationMapping_1.java
git add core/src/java/org/openmdx/base/accessor/jmi/spi/Jmi1ContainerInvocationHandler.java
git add core/src/java/org/openmdx/base/accessor/jmi/spi/Jmi1ObjectInvocationHandler.java
git add core/src/java/org/openmdx/base/accessor/jmi/spi/Jmi1ObjectPredicateInvocationHandler.java
git add core/src/java/org/openmdx/base/accessor/jmi/spi/Jmi1Package_1_0.java
git add core/src/java/org/openmdx/base/accessor/jmi/spi/Jmi1StructInvocationHandler.java
git add core/src/java/org/openmdx/base/accessor/jmi/spi/RefClass_1.java
git add core/src/java/org/openmdx/base/accessor/jmi/spi/RefContainer_1.java
git add core/src/java/org/openmdx/base/accessor/jmi/spi/RefException_1.java
git add core/src/java/org/openmdx/base/accessor/jmi/spi/RefMetaObject_1.java
git add core/src/java/org/openmdx/base/accessor/jmi/spi/RefObject_1.java
git add core/src/java/org/openmdx/base/accessor/jmi/spi/RefPackage_1.java
git add core/src/java/org/openmdx/base/accessor/jmi/spi/RefQuery_1.java
git add core/src/java/org/openmdx/base/accessor/jmi/spi/RefRootPackage_1.java
git add core/src/java/org/openmdx/base/accessor/jmi/spi/StandardMarshaller.java
git add core/src/java/org/openmdx/base/accessor/rest/AbstractContainer_1.java
git add core/src/java/org/openmdx/base/accessor/rest/Aspect_1.java
git add core/src/java/org/openmdx/base/accessor/rest/Container_1.java
git add core/src/java/org/openmdx/base/accessor/rest/DataManagerFactory_1.java
git add core/src/java/org/openmdx/base/accessor/rest/DataObjectManager_1.java
git add core/src/java/org/openmdx/base/accessor/rest/DataObject_1.java
git add core/src/java/org/openmdx/base/accessor/rest/FlushOrder.java
git add core/src/java/org/openmdx/base/accessor/rest/InboundConnection_2.java
git add core/src/java/org/openmdx/base/accessor/rest/ModelAwareFilter.java
git add core/src/java/org/openmdx/base/accessor/rest/Selection_1.java
git add core/src/java/org/openmdx/base/accessor/rest/TransactionalState_1.java
git add core/src/java/org/openmdx/base/accessor/rest/UnitOfWork_1.java
git add core/src/java/org/openmdx/base/accessor/rest/spi/AbstractFilter.java
git add core/src/java/org/openmdx/base/accessor/rest/spi/BasicCache_2.java
git add core/src/java/org/openmdx/base/accessor/rest/spi/Synchronization_2_0.java
git add core/src/java/org/openmdx/base/accessor/spi/AbstractDataObject_1.java
git add core/src/java/org/openmdx/base/accessor/spi/AbstractTransaction_1.java
git add core/src/java/org/openmdx/base/accessor/spi/MarshallingContainer_1.java
git add core/src/java/org/openmdx/base/accessor/spi/MarshallingObject_1.java
git add core/src/java/org/openmdx/base/accessor/spi/PersistenceManager_1_0.java
git add core/src/java/org/openmdx/base/accessor/view/ObjectView_1.java
git add core/src/java/org/openmdx/base/accessor/view/ViewManagerFactory_1.java
git add core/src/java/org/openmdx/base/accessor/view/ViewManager_1.java
git add core/src/java/org/openmdx/base/aop0/PlugIn_1.java
git add core/src/java/org/openmdx/base/aop0/PlugIn_1_0.java
git add core/src/java/org/openmdx/base/aop0/UpdateAvoidance.java
git add core/src/java/org/openmdx/base/aop0/UpdateAvoidance_1.java
git add core/src/java/org/openmdx/base/aop1/Aspect_1.java
git add core/src/java/org/openmdx/base/aop1/Extent_1.java
git add core/src/java/org/openmdx/base/aop1/PlugIn_1.java
git add core/src/java/org/openmdx/base/aop1/Removable_1.java
git add core/src/java/org/openmdx/base/aop2/AbstractObject.java
git add core/src/java/org/openmdx/base/aop2/PlugInContexts.java
git add core/src/java/org/openmdx/base/collection/AbstractMapDecorator.java
git add core/src/java/org/openmdx/base/collection/MapBackedSet.java
git add core/src/java/org/openmdx/base/collection/MarshallingCollection.java
git add core/src/java/org/openmdx/base/collection/MarshallingList.java
git add core/src/java/org/openmdx/base/collection/MarshallingSequentialList.java
git add core/src/java/org/openmdx/base/collection/MarshallingSet.java
git add core/src/java/org/openmdx/base/collection/MarshallingSortedMap.java
git add core/src/java/org/openmdx/base/collection/NullMaskingMap.java
git add core/src/java/org/openmdx/base/collection/Sets.java
git add core/src/java/org/openmdx/base/exception/RuntimeServiceException.java
git add core/src/java/org/openmdx/base/exception/ServiceException.java
git add core/src/java/org/openmdx/base/marshalling/ExceptionListenerMarshaller.java
git add core/src/java/org/openmdx/base/mof/cci/ModelHelper.java
git rm core/src/java/org/openmdx/base/mof/cci/Multiplicities.java
git add core/src/java/org/openmdx/base/mof/cci/Multiplicity.java
git add core/src/java/org/openmdx/base/mof/cci/Persistency.java
git add core/src/java/org/openmdx/base/mof/spi/ModelUtils.java
git add core/src/java/org/openmdx/base/mof/spi/Model_1Factory.java
git add core/src/java/org/openmdx/base/naming/Path.java
git add core/src/java/org/openmdx/base/naming/PathComponent.java
git add core/src/java/org/openmdx/base/naming/URI_1.java
git add core/src/java/org/openmdx/base/naming/XRI_1Marshaller.java
git add core/src/java/org/openmdx/base/persistence/cci/ConfigurableProperty.java
git add core/src/java/org/openmdx/base/persistence/cci/PersistenceHelper.java
git add core/src/java/org/openmdx/base/persistence/cci/UnitOfWork.java
git add core/src/java/org/openmdx/base/persistence/spi/AbstractPersistenceManager.java
git add core/src/java/org/openmdx/base/persistence/spi/AbstractPersistenceManagerFactory.java
git add core/src/java/org/openmdx/base/persistence/spi/DelegatingPersistenceManagerFactory.java
git add core/src/java/org/openmdx/base/persistence/spi/ExtentCollection.java
git add core/src/java/org/openmdx/base/persistence/spi/FilterCollection.java
git add core/src/java/org/openmdx/base/persistence/spi/MarshallingInstanceLifecycleListener.java
git add core/src/java/org/openmdx/base/persistence/spi/PersistenceCapableCollection.java
git add core/src/java/org/openmdx/base/persistence/spi/PersistenceManagers.java
git add core/src/java/org/openmdx/base/persistence/spi/Queries.java
git add core/src/java/org/openmdx/base/persistence/spi/QueryExtension.java
git add core/src/java/org/openmdx/base/persistence/spi/SharedObjects.java
git add core/src/java/org/openmdx/base/persistence/spi/StandardFetchGroup.java
git add core/src/java/org/openmdx/base/persistence/spi/StandardFetchPlan.java
git add core/src/java/org/openmdx/base/persistence/spi/TransientContainerId.java
git add core/src/java/org/openmdx/base/query/Condition.java
git add core/src/java/org/openmdx/base/query/ConditionType.java
git add core/src/java/org/openmdx/base/query/Filter.java
git add core/src/java/org/openmdx/base/query/LenientCharacterComparator.java
git add core/src/java/org/openmdx/base/query/OrderSpecifier.java
git add core/src/java/org/openmdx/base/resource/cci/ExtendedRecordFactory.java
git add core/src/java/org/openmdx/base/resource/spi/DelegatingIndexedRecord.java
git add core/src/java/org/openmdx/base/resource/spi/DelegatingMappedRecord.java
git add core/src/java/org/openmdx/base/resource/spi/RestInteractionSpec.java
git add core/src/java/org/openmdx/base/resource/spi/SingletonIndexedRecord.java
git add core/src/java/org/openmdx/base/resource/spi/SingletonMappedRecord.java
git add core/src/java/org/openmdx/base/resource/spi/StandardRecordFactory.java
git add core/src/java/org/openmdx/base/resource/spi/VariableSizeIndexedRecord.java
git add core/src/java/org/openmdx/base/resource/spi/VariableSizeMappedRecord.java
git add core/src/java/org/openmdx/base/rest/cci/QueryRecord.java
git add core/src/java/org/openmdx/base/rest/cci/RestConnectionSpec.java
git add core/src/java/org/openmdx/base/rest/spi/AbstractMappedRecord.java
git add core/src/java/org/openmdx/base/rest/spi/AbstractRestInteraction.java
git add core/src/java/org/openmdx/base/rest/spi/Facades.java
git add core/src/java/org/openmdx/base/rest/spi/ObjectRecord.java
git add core/src/java/org/openmdx/base/rest/spi/Object_2Facade.java
git add core/src/java/org/openmdx/base/rest/spi/QueryRecord.java
git add core/src/java/org/openmdx/base/rest/spi/Query_2Facade.java
git add core/src/java/org/openmdx/base/rest/spi/RestFormat.java
git add core/src/java/org/openmdx/base/text/conversion/SQLWildcards.java
git add core/src/java/org/openmdx/base/text/format/UUIDFormatter.java
git add core/src/java/org/openmdx/base/wbxml/DynamicPlugIn.java
git add core/src/java/org/openmdx/compatibility/application/dataprovider/transport/http/to/ejb/DataproviderServlet.java
git add core/src/java/org/openmdx/compatibility/base/dataprovider/layer/persistence/jdbc/Database_1Jpa.java
git add core/src/java/org/openmdx/compatibility/kernel/url/protocol/xri/ZipURLConnection.java
git add core/src/java/org/openmdx/kernel/collection/EnumMapping.java
git add core/src/java/org/openmdx/kernel/exception/BasicException.java
git add core/src/java/org/openmdx/kernel/exception/Throwables.java
git add core/src/java/org/openmdx/kernel/lightweight/naming/ManagedUserTransactionFactory.java
git add core/src/java/org/openmdx/kernel/lightweight/naming/NonManagedInitialContext.java
git add core/src/java/org/openmdx/kernel/lightweight/naming/NonManagedInitialContextFactory.java
git add core/src/java/org/openmdx/kernel/lightweight/naming/spi/HashMapContext.java
git add core/src/java/org/openmdx/kernel/lightweight/resource/LightweightConnectionManager.java
git rm core/src/java/org/openmdx/kernel/lightweight/sql/DatabaseConnectionFactory.java
git rm core/src/java/org/openmdx/kernel/lightweight/sql/LightweightXADataSource.java
git add core/src/java/org/openmdx/kernel/lightweight/sql/ManagedDatabaseConnectionFactory.java
git add core/src/java/org/openmdx/kernel/lightweight/transaction/LightweightTransaction.java
git add core/src/java/org/openmdx/kernel/lightweight/transaction/LightweightTransactionManager.java
git add core/src/java/org/openmdx/kernel/lightweight/transaction/LightweightTransactionSynchronizationRegistry.java
git add core/src/java/org/openmdx/kernel/lightweight/transaction/LightweightUserTransaction.java
git add core/src/java/org/openmdx/kernel/log/LoggerFactory.java
git add core/src/java/org/openmdx/kernel/log/SysLog.java
git add core/src/java/org/openmdx/kernel/url/protocol/AbstractURLConnection.java
git add core/src/java/org/openmdx/kernel/url/protocol/xri/ZipURLConnection.java
git add core/src/java/org/openmdx/kernel/xml/ValidatingDocumentBuilder.java
git add core/src/java/org/openmdx/state2/aop0/AbstractPlugIn_1.java
git add core/src/java/org/openmdx/state2/aop1/BasicState_1.java
git add core/src/java/org/openmdx/state2/aop1/DateState_1.java
git add core/src/java/org/openmdx/state2/aop1/DateTimeState_1.java
git add core/src/java/org/openmdx/state2/aop1/Extent_1.java
git add core/src/java/org/openmdx/state2/aop1/Object_1.java
git add core/src/java/org/openmdx/state2/aop1/PlugIn_1.java
git add core/src/java/org/openmdx/state2/aop1/StateCapableContainer_1.java
git add core/src/java/org/openmdx/state2/aop1/StateCapable_1.java
git add core/src/java/org/openmdx/state2/cci/DateStateViews.java
git add core/src/java/org/openmdx/state2/cci/FeatureComparator.java
git add core/src/java/org/openmdx/state2/cci/ObjectAndValidStateComparator.java
git add core/src/java/org/openmdx/state2/plugin/generic/StateMap_1.java
git add core/src/java/org/openmdx/state2/spi/Configuration.java
git add core/src/java/org/openmdx/uses/org/apache/commons/collections/OrderedIterator.java
git add core/src/java/org/openmdx/uses/org/apache/commons/collections/list/AbstractLinkedList.java
git add core/src/java/org/openmdx/uses/org/apache/commons/collections/list/CursorableLinkedList.java
git add core/src/java/org/openmdx/uses/org/apache/commons/fileupload/DiskFileUpload.java
git add core/src/java/org/openmdx/uses/org/apache/commons/fileupload/FileUploadBase.java
git add core/src/java/org/openmdx/uses/org/apache/commons/pool/impl/GenericKeyedObjectPool.java
git add core/src/java/org/openmdx/uses/org/apache/commons/pool/impl/GenericObjectPool.java
git add core/src/java/org/openmdx/uses/org/apache/commons/pool/impl/SoftReferenceObjectPool.java
git add core/src/java/org/openmdx/uses/org/apache/commons/pool/impl/StackKeyedObjectPool.java
git add core/src/java/org/openmdx/uses/org/apache/commons/pool/impl/StackObjectPool.java
git add core/src/java/org/w3c/cci2/ImmutableDate.java
git add core/src/java/org/w3c/cci2/ImmutableDateTime.java
git add core/src/java/org/w3c/spi2/Datatypes.java
git add core/src/java/org/w3c/spi2/Structures.java
git add core/src/jt/org/openmdx/application/dataprovider/kernel/LateBindingDataSource.jt
git add core/src/jt/org/openmdx/kernel/collection/ArraysExtension.jt
git add core/src/jt/org/openmdx/kernel/lightweight/sql/DatabaseConnection.jt
git add core/src/jt/org/openmdx/kernel/lightweight/sql/DatabaseConnectionFactory.jt
git add core/src/jt/org/openmdx/kernel/lightweight/sql/LightweightXAConnection.jt
git add core/src/jt/org/openmdx/kernel/lightweight/sql/LightweightXADataSource.jt
git add core/src/model/emf/diagrams/org.openmdx.base-Capabilities.umlclass
git add core/src/model/emf/diagrams/org.openmdx.generic1-Main.umlclass
git add core/src/model/emf/diagrams/org.openmdx.preferences1-Main.umlclass
git add core/src/model/emf/diagrams/org.openmdx.state2-Main.umlclass
git add core/src/model/emf/models.uml
git add core/src/model/emf/org.openmdx.base.uml
git rm core/src/model/emf/org.openmdx.compatibility.audit1.uml
git add core/src/model/rose/logicalView/org/openmdx.cat
git add core/src/model/rose/logicalView/org/openmdx/audit2.cat
git add core/src/model/rose/logicalView/org/openmdx/base.cat
git rm core/src/model/rose/logicalView/org/openmdx/compatibility/audit1.cat
git add core/src/model/rose/logicalView/org/openmdx/state2.cat
git rm core/src/resource/org/openmdx/compatibility/audti1/jpa3/Involved.openmdxjdo
git add core/src/resource/org/openmdx/kernel/application/deploy/jdbc-driver-sql.properties
git add ejb/.classpath
git add ejb/build.xml
git add ejb/src/java/org/openmdx/kernel/application/container/lightweight/LightweightContainer.java
git add ejb/src/java/org/openmdx/kernel/application/container/spi/ejb/AbstractHomeHandler.java
git add ejb/src/java/org/openmdx/kernel/application/container/spi/ejb/AbstractInvocationHandler.java
git add ejb/src/java/org/openmdx/kernel/application/container/spi/ejb/LocalTransactionContext.java
git add ejb/src/java/org/openmdx/kernel/application/deploy/enterprise/LightweightDeploymentManager.java
git add ejb/src/java/org/openmdx/kernel/application/deploy/enterprise/VerifyingDeploymentManager.java
git add ejb/src/java/org/openmdx/kernel/application/deploy/spi/LightweightClassLoader.java
git add ejb/src/java/org/openmdx/kernel/naming/component/java/javaURLContextFactory.java
git add ejb/src/java/org/openmdx/kernel/naming/container/openmdx/openmdxURLContextFactory.java
git add gitupdate.sh
git add installer/.project
git add installer/build.xml
git add installer/image/openmdx-sdk/INFO
git add installer/image/openmdx-sdk/LICENSE
git add installer/image/openmdx-sdk/README
git add installer/image/openmdx-sdk/bin/postinstallation.bat
git add installer/image/openmdx-sdk/bin/postinstallation.sh
git add installer/image/openmdx-sdk/bin/postinstaller.xml
git add installer/image/openmdx-sdk/favicon.ico
#	renamed:    installer/image/openmdx-tomcat-ejb/tomcat-openejb/logo.png -> installer/image/openmdx-sdk/logo.png
git add installer/image/openmdx-sdk/setenv.bat
git add installer/image/openmdx-sdk/setenv.sh
#	renamed:    installer/image/openmdx-tomcat-ejb/tomcat-openejb/splash.gif -> installer/image/openmdx-sdk/splash.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/LICENSE
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/NOTICE
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/RELEASE-NOTES
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/RUNNING.txt
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/bootstrap.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/catalina-tasks.xml
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/catalina.bat
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/catalina.sh
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/commons-daemon.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/cpappend.bat
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/digest.bat
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/digest.sh
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/jsvc.tar.gz
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/service.bat
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/setclasspath.bat
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/setclasspath.sh
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/shutdown.bat
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/shutdown.sh
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/startup.bat
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/startup.sh
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/tomcat-juli.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/tomcat-native.tar.gz
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/tomcat6.exe
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/tomcat6w.exe
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/tool-wrapper.bat
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/tool-wrapper.sh
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/version.bat
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/bin/version.sh
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/conf/catalina.policy
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/conf/catalina.properties
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/conf/context.xml
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/conf/logging.properties
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/conf/logging.properties.tomcat
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/conf/openejb.xml
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/conf/server.xml
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/conf/tomcat-users.xml
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/conf/web.xml
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/lib/annotations-api.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/lib/catalina-ant.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/lib/catalina-ha.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/lib/catalina-tribes.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/lib/catalina.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/lib/el-api.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/lib/jasper-el.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/lib/jasper-jdt.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/lib/jasper.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/lib/jsp-api.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/lib/openejb-javaagent.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/lib/servlet-api.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/lib/tomcat-coyote.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/lib/tomcat-dbcp.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/lib/tomcat-i18n-es.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/lib/tomcat-i18n-fr.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/lib/tomcat-i18n-ja.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/mx4j-impl.jar
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/0-openmdx-openejb.war
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/ROOT/RELEASE-NOTES.txt
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/ROOT/WEB-INF/web.xml
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/ROOT/admin/index.html
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/ROOT/asf-logo-wide.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/ROOT/build.xml
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/ROOT/favicon.ico
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/ROOT/index.html
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/ROOT/index.jsp
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/ROOT/openmdx.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/ROOT/tomcat-power.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/ROOT/tomcat.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/ROOT/tomcat.svg
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/host-manager/META-INF/context.xml
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/host-manager/WEB-INF/web.xml
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/host-manager/images/add.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/host-manager/images/asf-logo.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/host-manager/images/code.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/host-manager/images/design.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/host-manager/images/docs.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/host-manager/images/fix.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/host-manager/images/tomcat.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/host-manager/images/update.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/host-manager/images/void.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/host-manager/manager.xml
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/manager/401.jsp
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/manager/META-INF/context.xml
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/manager/WEB-INF/jsp/sessionDetail.jsp
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/manager/WEB-INF/jsp/sessionsList.jsp
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/manager/WEB-INF/web.xml
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/manager/images/add.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/manager/images/asf-logo.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/manager/images/code.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/manager/images/design.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/manager/images/docs.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/manager/images/fix.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/manager/images/tomcat.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/manager/images/update.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/manager/images/void.gif
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/manager/sessionDetail.jsp
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/manager/sessionsList.jsp
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/manager/status.xsd
git rm installer/image/openmdx-tomcat-ejb/apache-tomcat-6/webapps/manager/xform.xsl
git rm installer/image/openmdx-tomcat-ejb/bin/tomcat.bat
git rm installer/image/openmdx-tomcat-ejb/bin/tomcat.sh
git rm installer/image/openmdx-tomcat-ejb/tomcat-openejb/LICENSE
git rm installer/image/openmdx-tomcat-ejb/tomcat-openejb/README
git rm installer/image/openmdx-tomcat-ejb/tomcat-openejb/favicon.ico
git rm installer/image/openmdx-tomcat-ejb/tomcat-openejb/installer/bin/postinstallation.bat
git rm installer/image/openmdx-tomcat-ejb/tomcat-openejb/installer/bin/postinstallation.sh
git rm installer/image/openmdx-tomcat-ejb/tomcat-openejb/installer/bin/postinstaller.xml
git rm installer/image/openmdx-tomcat-ejb/tomcat-openejb/tomcat-openejb.ico
git rm installer/src/bitrock/tomcat-openejb.xml
git add installer/src/izpack/openmdx-sdk-install-definition.xml
git add installer/src/izpack/openmdx-sdk-unix-shortcut-spec.xml
git add installer/src/izpack/openmdx-sdk-userinput-spec.xml
git add installer/src/izpack/openmdx-sdk-windows-shortcut-spec.xml
git add openejb/.classpath
git add openejb/build.xml
git add openejb/openejb-3-properties.xml
git rm openejb/src/java/org/apache/openejb/tomcat/catalina/TomcatWebAppBuilder.java
git rm openejb/src/java/org/openmdx/catalina/core/ExtendedService.java
git rm openejb/src/java/org/openmdx/openejb/logging/JdkLogStream.java
git rm openejb/src/java/org/openmdx/openejb/logging/JdkLogStreamFactory.java
git rm openejb/src/resource/META-INF/MANIFEST.MF
git rm openejb/src/resource/org/openmdx/kernel/application/deploy/connector_1_0.dtd
git rm openejb/src/resource/org/openmdx/kernel/application/deploy/openmdx-connector_1_0.dtd
git rm openejb/src/resource/org/openmdx/kernel/application/deploy/openmdx-connector_1_1.dtd
git add openmdx.version.properties
git add opt/hsqldb/jre-1.6/hsqldb-2/lib/hsqldb.jar
git add opt/ibm/jre-1.5/lib/xml.jar
git add opt/postgresql/jre-1.6/postgresql-9/.classpath
git rm opt/postgresql/jre-1.6/postgresql-9/lib/postgresql-9.0.jdbc4.jar
git add opt/postgresql/jre-1.6/postgresql-9/lib/postgresql-9.1.jdbc4.jar
git add opt/postgresql/jre-1.6/postgresql-9/src/postgresql-9.0.jdbc4.zip
git add opt/radius/jre-1.6/TinyRadius-1/.classpath
git add opt/radius/jre-1.6/TinyRadius-1/.cvsignore
git add opt/radius/jre-1.6/TinyRadius-1/.project
git add opt/radius/jre-1.6/TinyRadius-1/doc/tiny-radius.javadoc.zip
git add opt/radius/jre-1.6/TinyRadius-1/lib/commons-logging.jar
git add opt/radius/jre-1.6/TinyRadius-1/lib/tiny-radius.jar
git add opt/radius/jre-1.6/TinyRadius-1/src/commons-logging.java.zip
git add opt/radius/jre-1.6/TinyRadius-1/src/tiny-radius.java.zip
git add osgi/jre-1.5/endorsed/.classpath
git add osgi/jre-1.5/endorsed/.cvsignore
git add osgi/jre-1.5/endorsed/.project
git add osgi/jre-1.5/endorsed/lib/datatypes.jar
git add osgi/jre-1.5/enterprise/.classpath
git add osgi/jre-1.5/enterprise/.cvsignore
git add osgi/jre-1.5/enterprise/.project
git add osgi/jre-1.5/enterprise/.settings/org.eclipse.jdt.core.prefs
git add osgi/jre-1.5/enterprise/lib/osgi.enterprise.jar
#	renamed:    osgi/jre-1.6/enterprise/lib/osgi.enterprise.persistence.jar -> osgi/jre-1.5/enterprise/lib/osgi.enterprise.persistence.jar
git add osgi/jre-1.5/enterprise/lib/osgi.enterprise.servlet.jar
git add osgi/jre-1.5/enterprise/lib/osgi.enterprise.transaction.jar
git add osgi/jre-1.5/enterprise/lib/osgi.enterprise.xml.jar
git add osgi/jre-1.5/extension/.classpath
git add osgi/jre-1.5/extension/.cvsignore
git add osgi/jre-1.5/extension/.project
git add osgi/jre-1.5/extension/.settings/org.eclipse.jdt.core.prefs
git add osgi/jre-1.5/extension/lib/commons-collections.jar
git add osgi/jre-1.5/extension/lib/commons-lang.jar
git add osgi/jre-1.5/extension/lib/concurrent.jar
git add osgi/jre-1.5/extension/lib/ejb.jar
git add osgi/jre-1.5/extension/lib/jcache.jar
git add osgi/jre-1.5/extension/lib/jdo2-api.jar
git add osgi/jre-1.5/extension/lib/junit.jar
#	renamed:    osgi/jre-1.6/extension/lib/mailapi.jar -> osgi/jre-1.5/extension/lib/mailapi.jar
git add osgi/jre-1.5/extension/lib/netscape-ldap.jar
git add osgi/jre-1.5/extension/lib/openjpa.jar
git add osgi/jre-1.5/extension/lib/resource.jar
git add osgi/jre-1.5/extension/lib/serp.jar
git add osgi/jre-1.6/enterprise/.classpath
git add osgi/jre-1.6/enterprise/lib/osgi.enterprise.persistence.jar
git add osgi/jre-1.6/extension/.classpath
git add osgi/jre-1.6/extension/lib/javax.enterprise.deploy.jar
git add osgi/jre-1.6/extension/lib/mail.jar
git add osgi/jre-1.6/extension/lib/openjpa.jar
git add osgi/jre-1.6/extension/src/jdo2-api.java.zip
git add osgi/jre-1.7/enterprise/.classpath
git add osgi/jre-1.7/enterprise/.cvsignore
git add osgi/jre-1.7/enterprise/.project
git add osgi/jre-1.7/enterprise/lib/osgi.enterprise.jar
git add osgi/jre-1.7/enterprise/lib/osgi.enterprise.persistence.jar
git add osgi/jre-1.7/enterprise/lib/osgi.enterprise.servlet.jar
git add osgi/jre-1.7/enterprise/lib/osgi.enterprise.transaction.jar
git add osgi/jre-1.7/enterprise/lib/osgi.enterprise.xml.jar
git add osgi/jre-1.7/extension/.classpath
git add osgi/jre-1.7/extension/.cvsignore
git add osgi/jre-1.7/extension/.project
git add osgi/jre-1.7/extension/lib/commons-collections.jar
git add osgi/jre-1.7/extension/lib/commons-lang.jar
git add osgi/jre-1.7/extension/lib/concurrent.jar
git add osgi/jre-1.7/extension/lib/ejb.jar
git add osgi/jre-1.7/extension/lib/javax.enterprise.deploy.jar
git add osgi/jre-1.7/extension/lib/jcache.jar
git add osgi/jre-1.7/extension/lib/jdo2-api.jar
git add osgi/jre-1.7/extension/lib/junit.jar
git add osgi/jre-1.7/extension/lib/mail.jar
git add osgi/jre-1.7/extension/lib/netscape-ldap.jar
git add osgi/jre-1.7/extension/lib/openjpa.jar
git add osgi/jre-1.7/extension/lib/resource.jar
git add osgi/jre-1.7/extension/lib/serp.jar
git add osgi/jre-1.7/extension/src/jdo2-api.java.zip
git add portal/.classpath
git add portal/CHANGE-LOG
git add portal/RELEASE-NOTES
git add portal/build.xml
git add portal/jre-1.7-properties.xml
git add portal/src/java/org/openmdx/portal/servlet/Action.java
git add portal/src/java/org/openmdx/portal/servlet/ActionFactory_1_0.java
git add portal/src/java/org/openmdx/portal/servlet/ApplicationContext.java
git rm portal/src/java/org/openmdx/portal/servlet/ApplicationContextConfiguration.java
git add portal/src/java/org/openmdx/portal/servlet/Codes.java
git add portal/src/java/org/openmdx/portal/servlet/DefaultActionFactory.java
git add portal/src/java/org/openmdx/portal/servlet/DefaultDataBinding.java
git add portal/src/java/org/openmdx/portal/servlet/DefaultPortalExtension.java
git rm portal/src/java/org/openmdx/portal/servlet/DefaultRoleMapper.java
git add portal/src/java/org/openmdx/portal/servlet/Filter.java
git add portal/src/java/org/openmdx/portal/servlet/Filters.java
git add portal/src/java/org/openmdx/portal/servlet/FindObjectsAutocompleter.java
git add portal/src/java/org/openmdx/portal/servlet/ObjectInspectorServlet.java
git add portal/src/java/org/openmdx/portal/servlet/ObjectReference.java
git add portal/src/java/org/openmdx/portal/servlet/PortalExtension_1_0.java
git add portal/src/java/org/openmdx/portal/servlet/QuickAccessor.java
git rm portal/src/java/org/openmdx/portal/servlet/RoleMapper_1_0.java
git add portal/src/java/org/openmdx/portal/servlet/UserSettings.java
git add portal/src/java/org/openmdx/portal/servlet/ValueListAutocompleter.java
git add portal/src/java/org/openmdx/portal/servlet/WebKeys.java
git add portal/src/java/org/openmdx/portal/servlet/action/AbstractAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/ActionPerformResult.java
git add portal/src/java/org/openmdx/portal/servlet/action/BoundAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/CancelAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/DeleteAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/EditAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/FindObjectAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/FindObjectsAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GetObjectAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridAddColumnFilterAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridAddObjectAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridAddOrderAnyAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridAddOrderAscendingAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridAddOrderDescendingAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridGetRowMenuAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridMoveDownObjectAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridMoveUpObjectAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridPageNextAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridPagePreviousAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridSelectFilterAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridSelectReferenceAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridSetAlignmentAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridSetAlignmentNarrowAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridSetAlignmentWideAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridSetColumnFilterAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridSetCurrentFilterAsDefaultAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridSetHideRowsOnInitAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridSetOrderAnyAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridSetOrderAscendingAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridSetOrderDescendingAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridSetPageAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridSetRowsOnInitAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/GridSetShowRowsOnInitAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/InvokeOperationAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/LogoffAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/MacroAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/MultiDeleteAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/NewObjectAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/ObjectGetAttributesAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/ReloadAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/SaveAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/SaveGridAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/SaveSettingsAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/SelectAndEditObjectAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/SelectAndNewObjectAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/SelectLocaleAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/SelectObjectAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/SelectPerspectiveAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/SelectViewportAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/SetPanelStateAction.java
git add portal/src/java/org/openmdx/portal/servlet/action/UnboundAction.java
git add portal/src/java/org/openmdx/portal/servlet/attribute/Attribute.java
git add portal/src/java/org/openmdx/portal/servlet/attribute/AttributeValue.java
git add portal/src/java/org/openmdx/portal/servlet/attribute/BinaryValue.java
git add portal/src/java/org/openmdx/portal/servlet/attribute/BooleanValue.java
git add portal/src/java/org/openmdx/portal/servlet/attribute/CodeValue.java
git add portal/src/java/org/openmdx/portal/servlet/attribute/DateValue.java
git add portal/src/java/org/openmdx/portal/servlet/attribute/NumberValue.java
git add portal/src/java/org/openmdx/portal/servlet/attribute/ObjectReferenceValue.java
git add portal/src/java/org/openmdx/portal/servlet/attribute/TextValue.java
git add portal/src/java/org/openmdx/portal/servlet/control/AbstractDashboardControl.java
git add portal/src/java/org/openmdx/portal/servlet/control/AttributePaneControl.java
git add portal/src/java/org/openmdx/portal/servlet/control/AttributeTabControl.java
git add portal/src/java/org/openmdx/portal/servlet/control/DashboardControl.java
git add portal/src/java/org/openmdx/portal/servlet/control/FieldGroupControl.java
git add portal/src/java/org/openmdx/portal/servlet/control/FormControl.java
git add portal/src/java/org/openmdx/portal/servlet/control/GridControl.java
git add portal/src/java/org/openmdx/portal/servlet/control/InspectorControl.java
git add portal/src/java/org/openmdx/portal/servlet/control/NavigationControl.java
git add portal/src/java/org/openmdx/portal/servlet/control/OperationPaneControl.java
git add portal/src/java/org/openmdx/portal/servlet/control/OperationTabControl.java
git add portal/src/java/org/openmdx/portal/servlet/control/PageEpilogControl.java
git add portal/src/java/org/openmdx/portal/servlet/control/ReferencePaneControl.java
git add portal/src/java/org/openmdx/portal/servlet/control/RootMenuControl.java
git add portal/src/java/org/openmdx/portal/servlet/control/SessionInfoControl.java
git add portal/src/java/org/openmdx/portal/servlet/control/ShowInspectorControl.java
git add portal/src/java/org/openmdx/portal/servlet/control/TabControl.java
git add portal/src/java/org/openmdx/portal/servlet/control/WizardTabControl.java
git add portal/src/java/org/openmdx/portal/servlet/control/WorkspaceDashboardControl.java
git rm portal/src/java/org/openmdx/portal/servlet/eventhandler/EditObjectEventHandler.java
git rm portal/src/java/org/openmdx/portal/servlet/eventhandler/EventHandlerHelper.java
git rm portal/src/java/org/openmdx/portal/servlet/eventhandler/FindObjectsEventHandler.java
git rm portal/src/java/org/openmdx/portal/servlet/eventhandler/GridEventHandler.java
git rm portal/src/java/org/openmdx/portal/servlet/eventhandler/HandleEventResult.java
git rm portal/src/java/org/openmdx/portal/servlet/eventhandler/LookupObjectEventHandler.java
git rm portal/src/java/org/openmdx/portal/servlet/eventhandler/SessionEventHandler.java
git rm portal/src/java/org/openmdx/portal/servlet/eventhandler/ShowObjectEventHandler.java
git add portal/src/java/org/openmdx/portal/servlet/loader/CodesLoader.java
git add portal/src/java/org/openmdx/portal/servlet/loader/DataLoader.java
git add portal/src/java/org/openmdx/portal/servlet/loader/FilterLoader.java
git add portal/src/java/org/openmdx/portal/servlet/loader/LayoutLoader.java
git add portal/src/java/org/openmdx/portal/servlet/loader/Loader.java
git add portal/src/java/org/openmdx/portal/servlet/loader/ReportsLoader.java
git add portal/src/java/org/openmdx/portal/servlet/loader/TextsLoader.java
git add portal/src/java/org/openmdx/portal/servlet/loader/UiLoader.java
git add portal/src/java/org/openmdx/portal/servlet/loader/WizardsLoader.java
git add portal/src/java/org/openmdx/portal/servlet/texts/Texts.java
git add portal/src/java/org/openmdx/portal/servlet/texts/Texts_1_0.java
git add portal/src/java/org/openmdx/portal/servlet/view/CompositeGrid.java
git add portal/src/java/org/openmdx/portal/servlet/view/EditObjectView.java
git add portal/src/java/org/openmdx/portal/servlet/view/Grid.java
git add portal/src/java/org/openmdx/portal/servlet/view/ObjectCreationResult.java
git add portal/src/java/org/openmdx/portal/servlet/view/ObjectView.java
git add portal/src/java/org/openmdx/portal/servlet/view/ReferenceGrid.java
git add portal/src/java/org/openmdx/portal/servlet/view/ReferencePane.java
git add portal/src/java/org/openmdx/portal/servlet/view/ShowObjectView.java
git add portal/src/java/org/openmdx/portal/servlet/view/TransientObjectView.java
git add portal/src/java/org/openmdx/portal/servlet/view/UserDefinedView.java
git add portal/src/java/org/openmdx/portal/servlet/view/View.java
git add portal/src/java/org/openmdx/portal/utility/CodeUtility.java
git add portal/src/java/org/openmdx/portal/utility/UiUtility.java
git add portal/src/java/org/openmdx/test/portal/servlet/TestThreadSafety.java
git add portal/src/java/org/openmdx/ui1/layer/application/Ui_1.java
git add portal/src/js/org/openmdx/portal/guicontrol.js
git add portal/src/war/openmdx-inspector.war/Login.jsp
git add portal/src/war/openmdx-inspector.war/Logoff.jsp
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/control/navigation/Default.groovy
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/layout/en_US/show-Default.jsp
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/texts/cs_CZ/texts.properties
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/texts/de_CH/texts.properties
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/texts/en_US/texts.properties
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/texts/es_CO/texts.properties
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/texts/es_MX/texts.properties
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/texts/fa_IR/texts.properties
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/texts/fr_FR/texts.properties
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/texts/it_IT/texts.properties
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/texts/ja_JP/texts.properties
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/texts/nl_NL/texts.properties
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/texts/pl_PL/texts.properties
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/texts/pt_BR/texts.properties
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/texts/ro_RO/texts.properties
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/texts/ru_RU/texts.properties
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/texts/sk_SK/texts.properties
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/texts/sv_SE/texts.properties
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/texts/tr_TR/texts.properties
git add portal/src/war/openmdx-inspector.war/WEB-INF/config/texts/zh_CN/texts.properties
git add portal/src/war/openmdx-inspector.war/_style/calendar-small.css
git add portal/src/war/openmdx-inspector.war/_style/default.css
git add portal/src/war/openmdx-inspector.war/_style/infovis.css
git add portal/src/war/openmdx-inspector.war/_style/mobile/iui.css
git add portal/src/war/openmdx-inspector.war/_style/n2default.css
git add portal/src/war/openmdx-inspector.war/_style/ssf.css
git add portal/src/war/openmdx-inspector.war/javascript/guicontrol.js
git add portal/src/war/openmdx-inspector.war/javascript/portal-all.js
git add portal/src/war/openmdx-inspector.war/wizards/Dashboard/QuickAccessDashlet.jsp
git add portal/src/war/openmdx-inspector.war/wizards/Dashboard/WorkspacesDashlet.jsp
git add portal/src/war/openmdx-inspector.war/wizards/en_US/DashboardWizard.jsp
git add portal/src/war/openmdx-inspector.war/wizards/en_US/WorkspaceDashboardWizard.jsp
git add security/RELEASE-NOTES
git add "security/etc/eclipse/openMDX 2 Security ~ Test RADIUS Packet.launch"
git add security/src/java/org/openmdx/resource/spi/AbstractManagedConnectionFactory.java
git add security/src/model/emf/diagrams/org.openmdx.security.authorization1-Main.umlclass
git add security/src/model/emf/diagrams/org.openmdx.security.realm1-Authorization.umlclass
git add security/src/model/emf/org.openmdx.security.authorization1.uml
git add security/src/model/emf/org.openmdx.security.realm1.uml
git add test-core.jre-1.5/.classpath
git add test-core.jre-1.5/.project
git add "test-core.jre-1.5/etc/eclipse/openMDX 2 ~ Test Datatypes.launch"
git add "test-core.jre-1.5/etc/eclipse/openMDX 2 ~ Test Duration Marshaller.launch"
git add "test-core.jre-1.5/etc/eclipse/openMDX 2 ~ Test Immutable Datatypes.launch"
git add "test-core.jre-1.5/etc/eclipse/openMDX 2 ~ Test Immutable Date.launch"
git add "test-core.jre-1.5/etc/eclipse/openMDX 2 ~ Test Main.launch"
git add "test-core.jre-1.5/etc/eclipse/openMDX 2 ~ Test Non-Managed Naming Context.launch"
git add test-core/build.xml
git add "test-core/etc/eclipse/openMDX 2 ~ Test Datatypes.launch"
git add "test-core/etc/eclipse/openMDX 2 ~ Test Duration Marshaller.launch"
git add "test-core/etc/eclipse/openMDX 2 ~ Test Main.launch"
git add "test-core/etc/eclipse/openMDX 2 ~ Test Structures.launch"
git add test-core/jre-1.7-properties.xml
git add test-core/src/java/test/mock/clock1/aop2/SegmentImpl.java
git add test-core/src/java/test/openmdx/app1/TestMain.java
git add test-core/src/java/test/openmdx/app1/aop2/PersonImpl.java
git add test-core/src/java/test/openmdx/app1/aop2/SegmentReferencesForeignPersonImpl.java
git add test-core/src/java/test/openmdx/app1/layer/application/HardWiredObjects_1.java
git add test-core/src/java/test/openmdx/app1/layer/application/PlugInReplacement_1.java
git add test-core/src/java/test/openmdx/application/dataprovider/layer/persistence/jdbc/TestDurationMarshaller.java
git add test-core/src/java/test/openmdx/application/rest/http/ServletPort.java
git add test-core/src/java/test/openmdx/base/naming/PathTest.java
git add test-core/src/java/test/openmdx/base/naming/WildcardTest.java
git add test-core/src/java/test/openmdx/base/resource/TestPerformance.java
git add test-core/src/java/test/openmdx/datatypes1/TestDatatypes.java
git add test-core/src/java/test/openmdx/kernel/lightweight/naming/TestNonManaged.java
git add test-core/src/java/test/openmdx/state2/TestDateState.java
git add test-core/src/java/test/openmdx/state2/TestState.java
git add test-core/src/java/test/w3c/cci2/TestImmutableDate.java
git add test-core/src/java/test/w3c/spi/TestImmutableDatatypes.java
git add test-core/src/java/test/w3c/spi2/ComplexStruct0_1Bean.java
git add test-core/src/java/test/w3c/spi2/ComplexStructListBean.java
git add test-core/src/java/test/w3c/spi2/PersonFormatNameAsResultBean.java
git add test-core/src/java/test/w3c/spi2/SimpleStruct0_1Bean.java
git add test-core/src/java/test/w3c/spi2/TestStructures.java
git add test-core/src/model/emf/diagrams/test.openmdx.app1-Invoice.umlclass
git add test-core/src/model/emf/diagrams/test.openmdx.datatypes1-Main.umlclass
git add test-core/src/model/emf/test.openmdx.app1.uml
git add test-core/src/resource/META-INF/app1Types.properties
git add test-core/src/resource/META-INF/datatypes1NativePlugIn.properties
git add test-core/src/resource/META-INF/jdoconfig.xml
git add test-core/src/resource/META-INF/openmdxmof.properties
git add test-core/src/resource/META-INF/standardDataprovider.properties
git add test-core/src/sql/oracle-10g/dbcreate-tables.sql
git add test-core/src/sql/oracle-10g/dbcreate-views.sql
git add test-core/src/sql/postgresql-8/dbcreate-tables.sql
git add test-core/src/sql/postgresql-8/dbcreate-views.sql
git add test-ejb/.classpath
git add test-ejb/src/java/test/openmdx/kernel/naming/EnvironmentTestCase.java
git add test-security/.classpath
git add test-security/src/java/test/openmdx/resource/ldap/TestLDAPConnector.java
git add test-security/src/java/test/openmdx/resource/pki/layer/application/Preferences_1.java
git add test-security/src/java/test/openmdx/resource/radius/TestPacket.java
git add test-security/src/java/test/openmdx/security/auth/TokenException.java
git add test-security/src/resource/test/openmdx/resource/radius/Access-Accept.cap
git add test-security/src/resource/test/openmdx/resource/radius/Access-Challenge-newPIN.cap
git add test-security/src/resource/test/openmdx/resource/radius/Access-Challenge-nextToken.cap
git add tomcat/.classpath
git add tomcat/.cvsignore
git add tomcat/.project
git add tomcat/build.xml
git add tomcat/etc/openjpa/enhance-persistence.xml
git add tomcat/src/java/org/openmdx/catalina/realm/ExtendedJDBCRealm.java
git add tomcat/src/java/org/openmdx/catalina/realm/HexUtils.java
