CREATE TABLE app1_DOC (
    object_referenceid bigint NOT NULL ,
    object_objectid varchar (200) NOT NULL ,
    object_idx integer NOT NULL ,
    created_at varchar (20),
    created_by varchar (200),
    modified_at varchar (20),
    modified_by varchar (200),
    object__class varchar (60),
    description varchar (100),
    content blob,
    keyword varchar (32) 
);

CREATE TABLE app1_GENERIC (
    object_referenceId bigint NOT NULL ,
    object_objectId text NOT NULL ,
    object_name varchar (64) NOT NULL ,
    object_val_string text,
    object_val_numeric decimal(18, 6),
    object_val_binary blob,
    object_idx int
);

CREATE TABLE app1_REF (
    object_referenceId bigint NOT NULL,
    object_reference text NOT NULL ,
    n integer,
    c$0 varchar (100),
    c$1 varchar (100),
    c$2 varchar (100),
    c$3 varchar (100),
    c$4 varchar (100),
    c$5 varchar (100),
    c$6 varchar (100),
    c$7 varchar (100),
    c$8 varchar (100),
    c$9 varchar (100)
);

CREATE TABLE app1_SLICED (
    object_referenceId bigint NOT NULL ,
    object_objectId varchar (200) NOT NULL ,
    object_idx integer NOT NULL ,
    created_at varchar (20),
    created_by varchar (200),
    modified_at varchar (20),
    modified_by varchar (200),
    object__class varchar (60),
    m1 varchar (200),
    last_name varchar (200),
    house_number varchar (200),
    city varchar (200),
    foreign_id varchar (200),
    postal_code varchar (200),
    description varchar (200),
    assigned_address varchar (200),
    product_id varchar (200),
    salutation varchar (200),
    street varchar (200),
    address_line varchar (200),
    address varchar (200),
    text varchar (200),
    birthdate varchar (200),
    place_of_birth varchar (200),
    member_of_group varchar (200),
    birthdate_as_date_time varchar (200),
    person_group varchar (200),
    country varchar (200),
    sex int,
    given_name varchar (200),
    product_group_id varchar (200)
);

CREATE TABLE audit_GENERIC (
    object_referenceId bigint NOT NULL ,
    object_objectId varchar (200) NOT NULL ,
    object_name varchar (64) NOT NULL ,
    object_val_string text,
    object_val_numeric decimal(18, 6),
    object_val_binary blob,
    object_idx int
);

CREATE TABLE audit_REF (
    object_referenceId bigint NOT NULL ,
    object_reference text NOT NULL ,
    n integer,
    c$0 varchar (100),
    c$1 varchar (100),
    c$2 varchar (100),
    c$3 varchar (100),
    c$4 varchar (100),
    c$5 varchar (100),
    c$6 varchar (100),
    c$7 varchar (100),
    c$8 varchar (100),
    c$9 varchar (100)
);

CREATE TABLE audit_SLICED (
    object_referenceId bigint NOT NULL ,
    object_objectId varchar (200) NOT NULL ,
    object_idx integer NOT NULL ,
    created_at varchar (20),
    created_by varchar (200),
    modified_at varchar (20),
    modified_by varchar (200),
    object__class varchar (60),
    m1 varchar (200),
    last_name varchar (200),
    house_number varchar (200),
    city varchar (200),
    foreign_id varchar (200),
    postal_code varchar (200),
    description varchar (200),
    assigned_address varchar (200),
    product_id varchar (200),
    salutation varchar (200),
    street varchar (200),
    address_line varchar (200),
    address varchar (200),
    text varchar (200),
    birthdate varchar (200),
    place_of_birth varchar (200),
    member_of_group varchar (200),
    birthdate_as_date_time varchar (200),
    person_group varchar (200),
    country varchar (200),
    sex int,
    given_name varchar (200),
    product_group_id varchar (200),
    involved varchar (200)
);

CREATE TABLE role1_GENERIC (
    object_referenceId bigint NOT NULL ,
    object_objectId varchar (200) NOT NULL ,
    object_name varchar (64) NOT NULL ,
    object_val_string text,
    object_val_numeric decimal(18, 6),
    object_val_binary blob,
    object_idx int
);

CREATE TABLE role1_REF (
    object_referenceId bigint NOT NULL ,
    object_reference text NOT NULL ,
    n integer,
    c$0 varchar (100),
    c$1 varchar (100),
    c$2 varchar (100),
    c$3 varchar (100),
    c$4 varchar (100),
    c$5 varchar (100),
    c$6 varchar (100),
    c$7 varchar (100),
    c$8 varchar (100),
    c$9 varchar (100),
    c$10 varchar (100),
    c$11 varchar (100)
);

CREATE TABLE role1_SLICED (
    object_referenceId bigint NOT NULL ,
    object_objectId varchar (200) NOT NULL ,
    object_idx integer NOT NULL ,
    created_at varchar (20),
    created_by varchar (200),
    modified_at varchar (20),
    modified_by varchar (200),
    object__class varchar (100),
    rara1$rcrara_name varchar (60),
    tfira1$object_class varchar (100),
    tfira2$object_class varchar (60),
    rara1$gggg varchar (60),
    tfira2$dddd varchar (60),
    tfira2$ident varchar (60),
    grp_ra$rcra_name varchar (60),
    rce_name varchar (60),
    tfira1$rcra_name varchar (60),
    ra1$dddd varchar (60),
    role4$object_class varchar (100),
    id_r_t_ara1$dddd varchar (60),
    clerk$business_phone varchar (60),
    id_r_t_ara2$dddd varchar (60),
    tfira0$rcra_name varchar (60),
    tfira0$object_class varchar (100),
    grp_ra$object_class varchar (100),
    role_c_r1$object_class varchar (100),
    role2$object_class varchar (100),
    role2$ident varchar (60),
    role_c_r1$dddd varchar (60),
    id_multira$object_class varchar (100),
    id_r_t_ara1$object_class varchar (100),
    extra_role$ident varchar (60),
    role3$object_class varchar (100),
    role3$rcrb_name varchar (60),
    role_c_r2$eeee varchar (60),
    id_multirb$object_class varchar (100),
    manager$object_class varchar (100),
    core_role varchar (60),
    manager$business_phone varchar (60),
    extra_role$object_class varchar (100),
    sgrp_rb$no_role varchar (60),
    id_r_t_ara2$object_class varchar (100),
    role4$rcrara_name varchar (60),
    sgrp_rb$ffff varchar (60),
    role1$object_class varchar (100),
    role_c_r1$ident varchar (60),
    grp_ra$dddd varchar (60),
    rara1$object_class varchar (100),
    id_r_t_ara2$ident varchar (60),
    grp_ra$group varchar (60),
    aaaa varchar (60),
    role_c_r1$rcra_name varchar (60),
    bbbb varchar (60),
    id_r_t_arara1$rcrara_name varchar (60),
    role_c_r2$dddd varchar (60),
    id_multirb$ident varchar (60),
    role1$ident varchar (60),
    name varchar (60),
    clerk$object_class varchar (100),
    tfira2$rcra_name varchar (60),
    clerk$division varchar (60),
    extra_role$rcra_name varchar (60),
    id_r_t_arara1$gggg varchar (60),
    role_c_r2$rcra_name varchar (60),
    role_c_r2$object_class varchar (100),
    ra1$ident varchar (60),
    id_r_t_ara1$ident varchar (60),
    role1$rcraName varchar (60),
    id_r_t_ara1$rcra_name varchar (60),
    role_b_id varchar (60),
    birthdate varchar (60),
    tfira0$ident varchar (60),
    role_c_r2$rcrae_name varchar (60),
    tfira1$dddd varchar (60),
    id_multira$rcra_name varchar (60),
    ra1$object_class varchar (60),
    id_r_t_ara2$rcra_name varchar (60),
    id_multirb$rcra_name varchar (60),
    rc_name varchar (60),
    role2$rcra_name varchar (60),
    extra_role$dddd varchar (60),
    id_multira$dddd varchar (60),
    manager$division varchar (60),
    id_r_t_arara1$object_class varchar (100),
    role_c_r2$ident varchar (60),
    id_multira$ident varchar (60),
    grp_ra$ident varchar (60),
    id_multirb$dddd varchar (60),
    sgrp_rb$rcrb_name varchar (60),
    tfira0$dddd varchar (60),
    sgrp_rb$object_class varchar (100),
    ra1$rcraName varchar (60),
    cccc varchar (60),
    tfira1$ident varchar (60),
    role_a_s1$rcra_name varchar (60),
    role_a_s1$object__class varchar (100),
    role_a_s1$ident varchar (60),
    role_a_s1$dddd varchar (60),
    role_b_f2$rcra_name varchar (60),
    role_b_f2$object__class varchar (100),
    role_b_f2$ident varchar (60),
    role_b_f2$eeee varchar (60),
    role_b_f2$dddd varchar (60),
    role_b_f2$rcrae_name varchar (60),
    role_b_f3$object__class varchar (100),
    role_c_r1$object__class varchar (100),
    role_c_r2$object__class varchar (100),
    role_c_r3$object__class varchar (100),
    role_c_r3$rcrb_name varchar (60),
    role_c_r3$rcrb_u_r_i varchar (200),
    role_c_r3$ffff varchar (60),
    non_exist$object__class varchar (100),
    role_r_a_r2$rcra_name varchar (60),
    role_r_a_r2$object__class varchar (100),
    role_r_a_r2$ident varchar (60),
    role_r_a_r2$dddd varchar (60),
    role_r_a_r2$eeee varchar (60),
    role_r_a_r2$rcrae_name varchar (60),
    role_r_a_r5$rcraera_name varchar (60),
    role_r_a_r5$object__class varchar (100),
    role_r_a_r5$hhhh varchar (60),
    role_e_x_c3$object__class varchar (100),
    role_e_x_c3$rcrb_name varchar (60),
    role_e_x_c3$ffff varchar (60),
    role_e_x_c3$rcrb_u_r_i varchar (200),
    r1$rcra_name varchar (60),
    r1$object__class varchar (100),
    r1$ident varchar (60),
    r1$dddd varchar (60),
    r2$object__class varchar (100),
    r2$rcrara_name varchar (60),
    r2$gggg varchar (60),
    role11$rcra_name varchar (60),
    role11$object__class varchar (100),
    role11$ident varchar (60),
    role11$dddd varchar (60),
    role12$object__class varchar (100),
    role12$rcrb_u_r_i varchar (200),
    role12$rcrb_name varchar (60),
    role12$ffff varchar (60),
    role_t_c1$object__class varchar (100),
    role_t_c1$rcrb_name varchar (60),
    role_t_c1$ffff varchar (60),
    role_t_c1$rcrb_u_r_i varchar (200),
    ra1$rcra_name varchar (60),
    ra1$object__class varchar (100),
    rara1$object__class varchar (100),
    tfira0$object__class varchar (100),
    tfira1$object__class varchar (100),
    tfira2$object__class varchar (100),
    extra_role$object__class varchar (100),
    id_multira$object__class varchar (100),
    id_multirb$object__class varchar (100),
    grp__ra$rcra_name varchar (60),
    grp__ra$object__class varchar (100),
    grp__ra$ident varchar (60),
    grp__ra$dddd varchar (60),
    grp__ra$group varchar (200),
    sgrp__rb$object__class varchar (100),
    sgrp__rb$ffff varchar (60),
    sgrp__rb$rcrb_name varchar (60),
    sgrp__rb$no_role varchar (200),
    role1$rcra_name varchar (60),
    role1$object__class varchar (100),
    role2$object__class varchar (100),
    role3$object__class varchar (100),
    role4$object__class varchar (100),
    id_r_t_ara1$object__class varchar (100),
    id_r_t_arara1$object__clas varchar (100),
    id_r_t_arara1$object__class varchar (100),
    id_r_t_ara2$object__class varchar (100),
    id_r_t_q_ara1$rcra_name varchar (60),
    id_r_t_q_ara1$object__class varchar (100),
    id_r_t_q_ara1$ident varchar (60),
    id_r_t_q_ara1$dddd varchar (60),
    id_r_t_q_ara2$rcra_name varchar (60),
    id_r_t_q_ara2$object__class varchar (100),
    id_r_t_q_ara2$ident varchar (60),
    id_r_t_q_ara2$dddd varchar (60),
    id_r_t_q_arb1$object__class varchar (100),
    id_r_t_q_arb1$rcrb_name varchar (60),
    id_r_t_q_arb2$object__class varchar (100),
    id_r_t_q_arb2$rcrb_name varchar (60)
);

CREATE TABLE state1_GENERIC (
    object_referenceId bigint NOT NULL ,
    object_objectId varchar (200) NOT NULL ,
    object_name varchar (64) NOT NULL ,
    object_val_string text,
    object_val_numeric decimal(18, 6),
    object_val_binary blob,
    object_idx int
);

CREATE TABLE state1_REF (
    object_referenceId bigint NOT NULL ,
    object_reference text NOT NULL ,
    n integer,
    c$0 varchar (100),
    c$1 varchar (100),
    c$2 varchar (100),
    c$3 varchar (100),
    c$4 varchar (100),
    c$5 varchar (100),
    c$6 varchar (100),
    c$7 varchar (100),
    c$8 varchar (100),
    c$9 varchar (100),
    c$10 varchar (100),
    c$11 varchar (100)
);

CREATE TABLE state1_SLICED (
    object_referenceId bigint NOT NULL ,
    object_objectId varchar (200) NOT NULL ,
    object_idx integer NOT NULL ,
    created_at varchar (20),
    created_by varchar (200),
    modified_at varchar (20),
    modified_by varchar (200),
    object__valid_from varchar (20),
    object__valid_to varchar (20),
    object__invalidated_at varchar (20),
    object__class varchar (100),
    object__state_number decimal(10, 0),
    object__state_id varchar (100),
    p$$object_parent__referenceid integer,
    p$$object_parent__objectid varchar (200),
    state_attr varchar (60),
    state_a varchar (200),
    val varchar (60),
    num varchar (60),
    state_a_derived varchar (60),
    value_a_derived varchar (60),
    multi_attr varchar (60),
    a1 varchar (60),
    a2 decimal(10, 0),
    rtr__r_a__$object__class varchar (60),
    rtr__r_a__$name varchar (60),
    rtr__r_a__$num varchar (60),
    role1211$object__class varchar (60),
    role1211$name varchar (60),
    role1211$num varchar (60),
    r1$object__class varchar (60),
    r1$name varchar (60),
    r1$num varchar (60),
    c_r__rt1$object__class varchar (60),
    c_r__rt1$name varchar (60),
    c_r__rt1$num varchar (60),
    r_r__rt1$object__class varchar (60),
    r_r__rt1$name varchar (60),
    r_r__rt1$num varchar (60),
    name varchar (60),
    aaaa varchar (60),
    rc_name varchar (60),
    bbbb varchar (60),
    role_b_id varchar (60),
    core_role varchar (60),
    long_values integer,
    any_u_r_i_val varchar (200),
    boolean_val varchar (10),
    date_val varchar (20),
    date_time_val varchar (20),
    decimal_val decimal(18, 6),
    duration_val varchar (10),
    integer_val decimal(10, 0),
    long_val integer,
    short_val decimal(10, 0),
    special_non_stated varchar (200)
);

CREATE TABLE test_GENERIC (
    object_rid bigint NOT NULL ,
    object_oid varchar (200) NOT NULL ,
    object_name varchar (64) NOT NULL ,
    object_val_string text,
    object_val_numeric decimal(18, 6),
    object_val_binary blob,
    object_idx int
);

CREATE TABLE test_REF (
    object_rid bigint NOT NULL ,
    object_reference text NOT NULL ,
    n integer,
    c$0 varchar (100),
    c$1 varchar (100),
    c$2 varchar (100),
    c$3 varchar (100),
    c$4 varchar (100),
    c$5 varchar (100),
    c$6 varchar (100),
    c$7 varchar (100),
    c$8 varchar (100),
    c$9 varchar (100)
);

CREATE TABLE test_SLB_GENERIC (
    object_rid bigint NOT NULL ,
    object_oid varchar (200) NOT NULL ,
    object_name varchar (64) NOT NULL ,
    object_val_string text,
    object_val_numeric decimal(18, 6),
    object_val_binary blob,
    object_idx int
);

CREATE TABLE test_SLB_SLICED (
    object_rid bigint NOT NULL ,
    object_oid varchar (200) NOT NULL ,
    object_idx integer NOT NULL ,
    created_at varchar (20),
    created_by varchar (200),
    modified_at varchar (20),
    modified_by varchar (200),
    object__class varchar (60),
    slb_type varchar (10),
    pos text,
    price decimal(18, 9),
    is_debit decimal(18, 9),
    is_long decimal(18, 9),
    price_currency varchar (10),
    value_date varchar (20),
    booking_date varchar (20),
    quantity decimal(18, 9),
    quantity_absolute decimal(18, 9),
    visibility varchar (10),
    admin_descr varchar (100),
    description varchar (100),
    cred_value blob,
    p$$object_parent__oid varchar (20),
    p$$object_parent__rid bigint,
    p$$pos__oid varchar (20),
    p$$pos__rid bigint,
    p$$pos_parent__oid varchar (50),
    p$$pos_parent__rid bigint
);

CREATE TABLE TEST_CB_SLICED (
    OBJECT_RID     BIGINT NOT NULL,
    OBJECT_IDX     INTEGER NOT NULL,
    CREATED_AT     VARCHAR(20),
    CREATED_BY     VARCHAR(200),
    MODIFIED_AT    VARCHAR(20),
    MODIFIED_BY    VARCHAR(200),
    OBJECT__CLASS  VARCHAR(60),
    CB_TYPE        VARCHAR(10),
    CANCELS_C_B    VARCHAR(200),
    ADVICE_TEXT    TEXT,
    OBJECT_OID     VARCHAR(120) NOT NULL
);
