/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openmdx_kernel_natives_Native */

#ifndef _Included_org_openmdx_kernel_natives_Native
#define _Included_org_openmdx_kernel_natives_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openmdx_kernel_natives_Native
 * Method:    jniConvertToCharSequence
 * Signature: ([B[CIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openmdx_kernel_natives_Native_jniConvertToCharSequence
  (JNIEnv *, jclass, jbyteArray, jcharArray, jint, jboolean);

/*
 * Class:     org_openmdx_kernel_natives_Native
 * Method:    jniConvertToByteSequence
 * Signature: ([C[BIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openmdx_kernel_natives_Native_jniConvertToByteSequence
  (JNIEnv *, jclass, jcharArray, jbyteArray, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif

